// Copyright Epic Games, Inc. All Rights Reserved.

#pragma once

#include "CoreMinimal.h"
#include "GridTypes.generated.h"

/**
 * What a cell is, for movement purposes.
 *
 * NoFloor is a generated state only -- it means the downward trace found nothing to
 * stand on, so the cell has no valid Z. Markers can never author it (see the
 * InvalidEnumValues meta on AGridCellMarkerBase::CellType).
 */
UENUM(BlueprintType)
enum class EGridCellType : uint8
{
	NoFloor			UMETA(DisplayName = "No Floor"),
	Walkable		UMETA(DisplayName = "Walkable"),
	Blocked			UMETA(DisplayName = "Blocked"),
	StageClear		UMETA(DisplayName = "Stage Clear"),
	Conditional		UMETA(DisplayName = "Conditional")
};

/** Why a cell is not walkable. Surfaced in the HUD so a refusal can be explained. */
UENUM(BlueprintType)
enum class EGridBlockReason : uint8
{
	None			UMETA(DisplayName = "Open"),
	NoFloorHit		UMETA(DisplayName = "No floor"),
	Slope			UMETA(DisplayName = "Too steep"),
	Clearance		UMETA(DisplayName = "Not enough headroom"),
	Marker			UMETA(DisplayName = "Blocked by designer")
};

/** Neighbour bits stored in FGridCellData::NeighborMask. Grid is 4-directional. */
namespace EGridDir
{
	enum Type : uint8
	{
		North	= 1 << 0,	// +Y
		East	= 1 << 1,	// +X
		South	= 1 << 2,	// -Y
		West	= 1 << 3	// -X
	};
}

/**
 * One grid cell. Generated by tracing, then possibly overwritten by marker overrides.
 *
 * NeighborMask is baked at generation time from the step-height rule, so pathfinding
 * never needs to look at FloorZ or at any generation setting.
 */
USTRUCT()
struct FGridCellData
{
	GENERATED_BODY()

	/** World Z of the floor under this cell's centre. Meaningless when Type == NoFloor. */
	UPROPERTY()
	float FloorZ = 0.0f;

	/**
	 * What tracing decided, before any marker override.
	 *
	 * Kept alongside the effective type so overrides can be re-applied from scratch without
	 * re-tracing: deleting a marker restores exactly what generation found, which a
	 * reconstruction from BlockReason alone could not do.
	 */
	UPROPERTY()
	EGridCellType GeneratedType = EGridCellType::NoFloor;

	UPROPERTY()
	EGridBlockReason GeneratedReason = EGridBlockReason::NoFloorHit;

	/** Effective type after overrides. This is what gameplay reads. */
	UPROPERTY()
	EGridCellType Type = EGridCellType::NoFloor;

	UPROPERTY()
	EGridBlockReason BlockReason = EGridBlockReason::NoFloorHit;

	/** EGridDir bits for 4-neighbours reachable by step height. Always symmetric. */
	UPROPERTY()
	uint8 NeighborMask = 0;

	/** Index into AGridActor::ConditionalRules, or INDEX_NONE. Only used when Type == Conditional. */
	UPROPERTY()
	int32 RuleIndex = INDEX_NONE;

	/** Floor slope in degrees. Debug/statistics only. */
	UPROPERTY()
	float SlopeDeg = 0.0f;
};

/**
 * One authored cell override, baked from the markers in the level.
 *
 * Serialized on the grid actor so a runtime regeneration (bRegenerateOnPlay) can re-apply
 * designer intent without the markers, which are editor-only and stripped on cook.
 */
USTRUCT()
struct FGridCellOverride
{
	GENERATED_BODY()

	UPROPERTY()
	FIntPoint Cell = FIntPoint::ZeroValue;

	UPROPERTY()
	EGridCellType Type = EGridCellType::Walkable;

	UPROPERTY()
	int32 RuleIndex = INDEX_NONE;
};
