// Copyright Epic Games, Inc. All Rights Reserved.

#pragma once

#include "CoreMinimal.h"
#include "GridTypes.generated.h"

/**
 * What a cell is, for movement purposes.
 *
 * NoFloor is a generated state only -- it means the downward trace found nothing to
 * stand on, so the cell has no valid Z. Markers can never author it (see the
 * InvalidEnumValues meta on AGridCellMarkerBase::CellType).
 */
UENUM(BlueprintType)
enum class EGridCellType : uint8
{
	NoFloor			UMETA(DisplayName = "No Floor"),
	Walkable		UMETA(DisplayName = "Walkable"),
	Blocked			UMETA(DisplayName = "Blocked"),
	StageClear		UMETA(DisplayName = "Stage Clear"),
	Conditional		UMETA(DisplayName = "Conditional")
};

/**
 * Why a cell is not walkable. Surfaced in the HUD so a refusal can be explained.
 *
 * Serialized as a uint8 inside FGridCellData, so new values may only be appended --
 * inserting one would silently reinterpret every already-saved cell.
 *
 * Object is the exception to that storage: it describes a runtime occupant (a puzzle
 * block), which changes as blocks slide, so it is only ever returned from a query and
 * never written into cell data.
 */
UENUM(BlueprintType)
enum class EGridBlockReason : uint8
{
	None			UMETA(DisplayName = "Open"),
	NoFloorHit		UMETA(DisplayName = "No floor"),
	Slope			UMETA(DisplayName = "Too steep"),
	Clearance		UMETA(DisplayName = "Not enough headroom"),
	Marker			UMETA(DisplayName = "Blocked by designer"),
	Object			UMETA(DisplayName = "Blocked by object")
};

/**
 * A 4-way direction as an editable property.
 *
 * EGridDir below is the bitmask form packed into FGridCellData::NeighborMask; it is a plain
 * namespaced enum and so cannot be a UPROPERTY. This is the authoring counterpart, used for
 * things a designer picks in the details panel (an elevator's door face, for instance).
 */
UENUM(BlueprintType)
enum class EGridDirection : uint8
{
	North	UMETA(DisplayName = "North (+Y)"),
	East	UMETA(DisplayName = "East (+X)"),
	South	UMETA(DisplayName = "South (-Y)"),
	West	UMETA(DisplayName = "West (-X)")
};

/** Neighbour bits stored in FGridCellData::NeighborMask. Grid is 4-directional. */
namespace EGridDir
{
	enum Type : uint8
	{
		North	= 1 << 0,	// +Y
		East	= 1 << 1,	// +X
		South	= 1 << 2,	// -Y
		West	= 1 << 3	// -X
	};
}

namespace LTTSGrid
{
	/** The neighbour bit matching an authored direction. */
	inline uint8 ToDirBit(EGridDirection Dir)
	{
		switch (Dir)
		{
		case EGridDirection::North:	return EGridDir::North;
		case EGridDirection::East:	return EGridDir::East;
		case EGridDirection::South:	return EGridDir::South;
		default:					return EGridDir::West;
		}
	}

	/** Cell offset of one step in a direction. */
	inline FIntPoint DirOffset(EGridDirection Dir)
	{
		switch (Dir)
		{
		case EGridDirection::North:	return FIntPoint(0, 1);
		case EGridDirection::East:	return FIntPoint(1, 0);
		case EGridDirection::South:	return FIntPoint(0, -1);
		default:					return FIntPoint(-1, 0);
		}
	}

	/**
	 * Turn a direction by quarter turns.
	 *
	 * One positive turn is +90 degrees of yaw, which sends East to North (in a top-down
	 * view with +X up and +Y right, that reads as clockwise). In the enum order
	 * North, East, South, West that is a step *back* by one index.
	 */
	inline EGridDirection RotateDirection(EGridDirection Dir, int32 QuarterTurns)
	{
		const int32 Index = static_cast<int32>(Dir);
		const int32 Turned = ((Index - QuarterTurns) % 4 + 4) % 4;
		return static_cast<EGridDirection>(Turned);
	}

	/**
	 * Actors carrying this tag are skipped by grid generation traces.
	 *
	 * Puzzle blocks stand on the floor and would otherwise bake themselves in as Blocked
	 * cells, freezing the level layout at whatever positions they happened to be authored
	 * at. A function-local static keeps FName construction out of static init.
	 */
	inline const FName& GenerationIgnoreTag()
	{
		static const FName Tag(TEXT("GridTraceIgnore"));
		return Tag;
	}
}

/**
 * One grid cell. Generated by tracing, then possibly overwritten by marker overrides.
 *
 * NeighborMask is baked at generation time from the step-height rule, so pathfinding
 * never needs to look at FloorZ or at any generation setting.
 */
USTRUCT()
struct FGridCellData
{
	GENERATED_BODY()

	/** World Z of the floor under this cell's centre. Meaningless when Type == NoFloor. */
	UPROPERTY()
	float FloorZ = 0.0f;

	/**
	 * What tracing decided, before any marker override.
	 *
	 * Kept alongside the effective type so overrides can be re-applied from scratch without
	 * re-tracing: deleting a marker restores exactly what generation found, which a
	 * reconstruction from BlockReason alone could not do.
	 */
	UPROPERTY()
	EGridCellType GeneratedType = EGridCellType::NoFloor;

	UPROPERTY()
	EGridBlockReason GeneratedReason = EGridBlockReason::NoFloorHit;

	/** Effective type after overrides. This is what gameplay reads. */
	UPROPERTY()
	EGridCellType Type = EGridCellType::NoFloor;

	UPROPERTY()
	EGridBlockReason BlockReason = EGridBlockReason::NoFloorHit;

	/** EGridDir bits for 4-neighbours reachable by step height. Always symmetric. */
	UPROPERTY()
	uint8 NeighborMask = 0;

	/** Index into AGridActor::ConditionalRules, or INDEX_NONE. Only used when Type == Conditional. */
	UPROPERTY()
	int32 RuleIndex = INDEX_NONE;

	/** Floor slope in degrees. Debug/statistics only. */
	UPROPERTY()
	float SlopeDeg = 0.0f;
};

/**
 * One authored cell override, baked from the markers in the level.
 *
 * Serialized on the grid actor so a runtime regeneration (bRegenerateOnPlay) can re-apply
 * designer intent without the markers, which are editor-only and stripped on cook.
 */
USTRUCT()
struct FGridCellOverride
{
	GENERATED_BODY()

	UPROPERTY()
	FIntPoint Cell = FIntPoint::ZeroValue;

	UPROPERTY()
	EGridCellType Type = EGridCellType::Walkable;

	UPROPERTY()
	int32 RuleIndex = INDEX_NONE;
};
